### ISSUE TITLE
Призрак над кнопкой

### ISSUE THREAD

**Issue by comerc** [mailru/FileAPI#295]
`input[type=file]` для этих целей плохо подходит, т.к. невозможно его установить к требуемым размерам кнопки. Применим технику наслоения div-ов, которая уже реализована для флеша (вовсе не dummy, как оно презрительно названо в коде). 😊

На примере Метеора. 
```jade
template(name="photo")
  a.js-fileapi-wrapper.btn.btn-success(href="#")
    i.fa.fa-camera
    .js-ghost
    input(type="file" name="filedata")
```
внутри `.js-fileapi-wrapper` добавлен `.js-ghost` перед `input[type="file"]` и на том же уровне.

```css
.js-fileapi-wrapper {
  position: relative;
}
.js-fileapi-wrapper .js-ghost {
  position: absolute;
  top: 0; bottom: 0; left: 0; right: 0;
  width: 100%; height: 100%;
}
.js-fileapi-wrapper input {
  display: none;
}
```
`.js-ghost` перекрывает кнопку, а `input[type=file]` теперь спрятан (сколько насмотрелся кастомных контролов, всегда так поступают).

```coffee
Template.photo.events
  'click a.js-fileapi-wrapper': (event, template) ->
    template.$('input[type="file"]').click()
  'click input[type="file"]': (event) ->
    event.stopPropagation()
```
это поведение без флеша; т.к. `input[type="file"]` должен быть вложен в `.js-fileapi-wrapper`, нужно обойти зацикливание с помощью `event.stopPropagation()`.

А теперь костылим для флеша событие `mouseover` в FileAPI.js:
```js
nextElementSibling: function ( el ) {
  do { el = el.nextSibling } while ( el && el.nodeType !== 1 );
  return el;
},

mouseover: function (evt){
  var target = api.event.fix(evt).target;

  if (/js-ghost/.test(target.className)) {
    target = target.nextElementSibling || flash.nextElementSibling(target);

  // if( /input/i.test(target.nodeName) && target.type == 'file' && !target.disabled ){
```
Просто надо подменить `target`, и жизнь наша сразу улучшится.

PS Хотя... с реализацией FileAPI для флеша хочется решить еще пару вопросов: a:hover, [enter].
